const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Plugins.Mouse,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Behaviors.solid,
		C3.Behaviors.Fade,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.MoveTo.Acts.SetSpeed,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{ScrollTo: 0},
	{spr_player: 0},
	{Mouse: 0},
	{MoveTo: 0},
	{spr_enemy: 0},
	{ID: 0},
	{spr_spawner: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{spr_bullet: 0},
	{tb_hudBG: 0},
	{txt_score: 0},
	{txt_level: 0},
	{txt_clock: 0},
	{Sine: 0},
	{spr_bomb: 0},
	{spr_bomb2: 0},
	{txt_bomb: 0},
	{tb_flash: 0},
	{Particles: 0},
	{txt_countDown: 0},
	{tb_gameOverScreen: 0},
	{txt_generic: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{txt_hiScore: 0},
	{spr_crossHair: 0},
	{Sprite: 0},
	{Texto: 0},
	{Sprite2: 0},
	{Sólido: 0},
	{fundocut: 0},
	{Esmaecer: 0},
	{Texto2: 0},
	{Sprite3: 0},
	{fundocut2: 0},
	{Texto3: 0},
	{fundocut3: 0},
	{Texto4: 0},
	{fundocut4: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite4: 0},
	{Projétil: 0},
	{MoverPara: 0},
	{Boss: 0},
	{Sprite6: 0},
	{"8Direções": 0},
	{RestritoAoLayout: 0},
	{spr_player2: 0},
	{spawnSpeed: 0},
	{enemySpeed: 0},
	{spawnerRNG: 0},
	{score: 0},
	{level: 0},
	{clock: 0},
	{bombs: 0},
	{gameOver: 0},
	{countDownTimer: 0},
	{hiScore: 0},
	{gameState: 0}
];

self.InstanceType = {
	spr_player: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	spr_enemy: class extends self.ISpriteInstance {},
	spr_spawner: class extends self.ISpriteInstance {},
	spr_bullet: class extends self.ISpriteInstance {},
	tb_hudBG: class extends self.ITiledBackgroundInstance {},
	txt_score: class extends self.ITextInstance {},
	txt_level: class extends self.ITextInstance {},
	txt_clock: class extends self.ITextInstance {},
	spr_bomb: class extends self.ISpriteInstance {},
	spr_bomb2: class extends self.ISpriteInstance {},
	txt_bomb: class extends self.ITextInstance {},
	tb_flash: class extends self.ITiledBackgroundInstance {},
	Particles: class extends self.IParticlesInstance {},
	txt_countDown: class extends self.ITextInstance {},
	tb_gameOverScreen: class extends self.ITiledBackgroundInstance {},
	txt_generic: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	txt_hiScore: class extends self.ITextInstance {},
	spr_crossHair: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	fundocut: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	fundocut2: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	fundocut3: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	fundocut4: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Boss: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	spr_player2: class extends self.ISpriteInstance {}
}